#!/bin/bash
music_file=~/.local/share/music_list.csv

#main body that always plays the music
main (){
	echo $vid_selected
	vid=$(grep "$vid_selected" $music_file|cut -d ',' -f 2)
	mpv --no-vid "$vid"
}

#allowing to choose $vid_selected
choosing (){
	vid_selected="$(cut -d ',' -f 1 $music_file|fzf --reverse)"
	[[ $vid_selected == "" ]] && exit 0
}

#setting $vid_selected to be random
shuffle (){
	local previous_vid=$vid_selected
	vid_selected=$(cut -d ',' -f 1 $music_file|shuf -n 1)
	[[ $vid_selected == $previous_vid ]] && shuffle
}

#to see which option they have chosen
if [[ $1 == "-l" ]];then
	todo=shuffle
else
	todo=choosing
fi

#The main loop
while true;do
	$todo
	main
done
