#!/bin/bash
music_file=~/.local/share/music_list.csv

#adding songs function
adding_songs (){
	echo -en "Enter name of song \e[1;31m>\e[0m "
	read song_added
	echo -en "Enter link of song \e[1;31m>\e[0m "
	read song_link
	echo "$song_added,$song_link" >> $music_file
	exit 0
}

#main body that always plays the music
main (){
	echo $vid_selected
	vid=$(grep "$vid_selected" $music_file|cut -d ',' -f 2)
	mpv --no-vid "$vid"
}

#allowing to choose $vid_selected
choosing (){
	vid_selected="$(cut -d ',' -f 1 $music_file|sort|fzf --reverse )"
	[[ $vid_selected == "" ]] && exit 0
	main
}

online_searching (){
	ytfzf -m $1
	choosing
}

#setting $vid_selected to be random
shuffle (){
	local previous_vid=$vid_selected
	vid_selected=$(cut -d ',' -f 1 $music_file|shuf -n 1)
	#this still causes previoud_vid to be set twice
	#can fix by making previous_vid global
	[[ $vid_selected == $previous_vid ]] && shuffle
	main
}

#to see which option they have chosen
case "$1" in
	-s|--shuffle)	todo=shuffle ;;
	-a|--adding)	todo=adding_songs ;;

	-o|--online)	shift
					online_searching "$*"
					;;
	*)				todo=choosing ;;
esac

#The main loop
while true;do
	$todo
done
